#!/bin/sh
set -e

# Run CI tests before pushing
echo "Running CI tests..."

echo "[1/3] Running formatter..."
sh ./ci/run_formatter.sh

echo "[2/3] Running linter..."
sh ./ci/run_linter.sh

echo "[3/3] Running tests..."
sh ./ci/run_tests.sh
